[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.7.1"
tokio = { version = "1.17", features = [ "rt-multi-thread"] }
prost = "0.10"

[build-dependencies]
tonic-build = "0.7"

[profile.release]
strip = true
lto = true
